# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setGeometry(QtCore.QRect(10, 40, 781, 541))
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.stackedWidgetPage_addSentence = QtWidgets.QWidget()
        self.stackedWidgetPage_addSentence.setObjectName("stackedWidgetPage_addSentence")
        self.pushButton = QtWidgets.QPushButton(self.stackedWidgetPage_addSentence)
        self.pushButton.setGeometry(QtCore.QRect(10, 80, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_sentence = QtWidgets.QTextEdit(self.stackedWidgetPage_addSentence)
        self.textEdit_sentence.setGeometry(QtCore.QRect(10, 30, 241, 41))
        self.textEdit_sentence.setObjectName("textEdit_sentence")
        self.textEdit_translation = QtWidgets.QTextEdit(self.stackedWidgetPage_addSentence)
        self.textEdit_translation.setGeometry(QtCore.QRect(260, 30, 241, 41))
        self.textEdit_translation.setObjectName("textEdit_translation")
        self.label_sentence = QtWidgets.QLabel(self.stackedWidgetPage_addSentence)
        self.label_sentence.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.label_sentence.setObjectName("label_sentence")
        self.label_translation = QtWidgets.QLabel(self.stackedWidgetPage_addSentence)
        self.label_translation.setGeometry(QtCore.QRect(260, 10, 61, 21))
        self.label_translation.setObjectName("label_translation")
        self.pushButton_addSentence = QtWidgets.QPushButton(self.stackedWidgetPage_addSentence)
        self.pushButton_addSentence.setGeometry(QtCore.QRect(210, 80, 101, 23))
        self.pushButton_addSentence.setObjectName("pushButton_addSentence")
        self.stackedWidget_main.addWidget(self.stackedWidgetPage_addSentence)
        self.stackedWidgetPage_addLanguage = QtWidgets.QWidget()
        self.stackedWidgetPage_addLanguage.setObjectName("stackedWidgetPage_addLanguage")
        self.frame = QtWidgets.QFrame(self.stackedWidgetPage_addLanguage)
        self.frame.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 81, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_addLang = QtWidgets.QPushButton(self.frame)
        self.pushButton_addLang.setGeometry(QtCore.QRect(184, 100, 91, 23))
        self.pushButton_addLang.setObjectName("pushButton_addLang")
        self.lineEdit_language = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_language.setGeometry(QtCore.QRect(90, 30, 161, 20))
        self.lineEdit_language.setObjectName("lineEdit_language")
        self.stackedWidget_main.addWidget(self.stackedWidgetPage_addLanguage)
        self.stackedWidgetPage_viewTerms = QtWidgets.QWidget()
        self.stackedWidgetPage_viewTerms.setObjectName("stackedWidgetPage_viewTerms")
        self.tableWidget_terms = QtWidgets.QTableWidget(self.stackedWidgetPage_viewTerms)
        self.tableWidget_terms.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.tableWidget_terms.setObjectName("tableWidget_terms")
        self.tableWidget_terms.setColumnCount(0)
        self.tableWidget_terms.setRowCount(0)
        self.stackedWidget_main.addWidget(self.stackedWidgetPage_viewTerms)
        self.stackedWidgetPage_viewSentences = QtWidgets.QWidget()
        self.stackedWidgetPage_viewSentences.setObjectName("stackedWidgetPage_viewSentences")
        self.tableWidget_sentences = QtWidgets.QTableWidget(self.stackedWidgetPage_viewSentences)
        self.tableWidget_sentences.setGeometry(QtCore.QRect(10, 10, 751, 192))
        self.tableWidget_sentences.setObjectName("tableWidget_sentences")
        self.tableWidget_sentences.setColumnCount(0)
        self.tableWidget_sentences.setRowCount(0)
        self.textEdit_currSentence = QtWidgets.QTextEdit(self.stackedWidgetPage_viewSentences)
        self.textEdit_currSentence.setGeometry(QtCore.QRect(10, 240, 271, 71))
        self.textEdit_currSentence.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_currSentence.setObjectName("textEdit_currSentence")
        self.lineEdit_term = QtWidgets.QLineEdit(self.stackedWidgetPage_viewSentences)
        self.lineEdit_term.setGeometry(QtCore.QRect(10, 340, 171, 20))
        self.lineEdit_term.setReadOnly(True)
        self.lineEdit_term.setObjectName("lineEdit_term")
        self.label_term = QtWidgets.QLabel(self.stackedWidgetPage_viewSentences)
        self.label_term.setGeometry(QtCore.QRect(10, 320, 91, 21))
        self.label_term.setObjectName("label_term")
        self.label_termTranslation = QtWidgets.QLabel(self.stackedWidgetPage_viewSentences)
        self.label_termTranslation.setGeometry(QtCore.QRect(10, 370, 91, 21))
        self.label_termTranslation.setObjectName("label_termTranslation")
        self.lineEdit_termTranslation = QtWidgets.QLineEdit(self.stackedWidgetPage_viewSentences)
        self.lineEdit_termTranslation.setGeometry(QtCore.QRect(10, 390, 171, 20))
        self.lineEdit_termTranslation.setObjectName("lineEdit_termTranslation")
        self.pushButton_addTerm = QtWidgets.QPushButton(self.stackedWidgetPage_viewSentences)
        self.pushButton_addTerm.setGeometry(QtCore.QRect(200, 390, 81, 23))
        self.pushButton_addTerm.setObjectName("pushButton_addTerm")
        self.label_currSentence = QtWidgets.QLabel(self.stackedWidgetPage_viewSentences)
        self.label_currSentence.setGeometry(QtCore.QRect(10, 220, 91, 21))
        self.label_currSentence.setObjectName("label_currSentence")
        self.stackedWidget_main.addWidget(self.stackedWidgetPage_viewSentences)
        self.comboBox_languages = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_languages.setGeometry(QtCore.QRect(120, 10, 151, 22))
        self.comboBox_languages.setObjectName("comboBox_languages")
        self.label_currLang = QtWidgets.QLabel(self.centralwidget)
        self.label_currLang.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.label_currLang.setObjectName("label_currLang")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSentences = QtWidgets.QMenu(self.menuBar)
        self.menuSentences.setObjectName("menuSentences")
        self.menuLanguages = QtWidgets.QMenu(self.menuBar)
        self.menuLanguages.setObjectName("menuLanguages")
        self.menuTerms = QtWidgets.QMenu(self.menuBar)
        self.menuTerms.setObjectName("menuTerms")
        MainWindow.setMenuBar(self.menuBar)
        self.action_addSentence = QtWidgets.QAction(MainWindow)
        self.action_addSentence.setObjectName("action_addSentence")
        self.action_addLanguage = QtWidgets.QAction(MainWindow)
        self.action_addLanguage.setObjectName("action_addLanguage")
        self.actionAdd_Term = QtWidgets.QAction(MainWindow)
        self.actionAdd_Term.setObjectName("actionAdd_Term")
        self.action_viewTerms = QtWidgets.QAction(MainWindow)
        self.action_viewTerms.setObjectName("action_viewTerms")
        self.action_viewSentences = QtWidgets.QAction(MainWindow)
        self.action_viewSentences.setObjectName("action_viewSentences")
        self.menuSentences.addAction(self.action_addSentence)
        self.menuSentences.addAction(self.action_viewSentences)
        self.menuLanguages.addAction(self.action_addLanguage)
        self.menuTerms.addAction(self.actionAdd_Term)
        self.menuTerms.addAction(self.action_viewTerms)
        self.menuBar.addAction(self.menuSentences.menuAction())
        self.menuBar.addAction(self.menuLanguages.menuAction())
        self.menuBar.addAction(self.menuTerms.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Learning with Sentences"))
        self.pushButton.setText(_translate("MainWindow", "get from tatoeba"))
        self.label_sentence.setText(_translate("MainWindow", "Sentence"))
        self.label_translation.setText(_translate("MainWindow", "Translation"))
        self.pushButton_addSentence.setText(_translate("MainWindow", "Add sentence"))
        self.label.setText(_translate("MainWindow", "Study Languge:"))
        self.label_2.setText(_translate("MainWindow", "New Language"))
        self.pushButton_addLang.setText(_translate("MainWindow", "Add language"))
        self.label_term.setText(_translate("MainWindow", "Term:"))
        self.label_termTranslation.setText(_translate("MainWindow", "Translation:"))
        self.pushButton_addTerm.setText(_translate("MainWindow", "Add Term"))
        self.label_currSentence.setText(_translate("MainWindow", "Current Sentence:"))
        self.label_currLang.setText(_translate("MainWindow", "Current language:"))
        self.menuSentences.setTitle(_translate("MainWindow", "Sentences"))
        self.menuLanguages.setTitle(_translate("MainWindow", "Languages"))
        self.menuTerms.setTitle(_translate("MainWindow", "Terms"))
        self.action_addSentence.setText(_translate("MainWindow", "Add Sentence"))
        self.action_addLanguage.setText(_translate("MainWindow", "Add Language"))
        self.actionAdd_Term.setText(_translate("MainWindow", "Add Term"))
        self.action_viewTerms.setText(_translate("MainWindow", "View Terms"))
        self.action_viewSentences.setText(_translate("MainWindow", "View Sentences"))

